services:

# =================================
# Postgres
# =================================
  postgres-prod:
    image: postgres:16-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - internal_network
    restart: unless-stopped

# =================================
# NestJS
# =================================
  api-prod:
    image: phall168k/devop-learning-final-app-backend:latest
    environment:
      NODE_ENV: production
      API_PORT: ${API_PORT}
      API_PREFIX: ${API_PREFIX}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    scale: 2
    expose:
      - "8000"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:${API_PORT}/api/health').then((r) => { if (!r.ok) process.exit(1); }).catch(() => process.exit(1));",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      postgres-prod:
        condition: service_healthy
    networks:
      - internal_network
    restart: unless-stopped

# =================================
# NuxtJS
# =================================
  frontend-prod:
    image: phall168k/devop-learning-final-app-frontend:latest
    container_name: frontend-prod
    environment:
      NODE_ENV: production
      HOST: ${HOST}
      PORT: ${PORT}
    expose:
      - "${PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:3000').then((r) => { if(!r.ok) process.exit(1); }).catch(() => process.exit(1));"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      api-prod:
        condition: service_healthy
    networks:
      - internal_network
    restart: unless-stopped

# =================================
# NGINX
# =================================
  load-balancer-prod:
    image: nginx:alpine
    container_name: load-balancer-prod
    environment:
      API_PORT: ${API_PORT}
      PORT: ${PORT}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      NGINX_MAX_BODY: ${NGINX_MAX_BODY}
    ports:
      - "80:80"
    depends_on:
      frontend-prod:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    networks:
      - internal_network
      - external_network
    restart: unless-stopped

# =================================
# Volumes
# =================================
volumes:
  postgres_prod_data:

# =================================
# Network Setup
# =================================
networks:
  internal_network:
    driver: bridge
    internal: true
  external_network:
    driver: bridge

